

# https://github.com/sheerun/vim-polyglot
# neomake
# editorconfig

echo
echo
echo
echo '" ====================='
echo '" === AUTOGENERATED ==='
echo '" ====================='
echo
echo
echo

cat << EndOfMessage
set nocompatible
syntax on
set t_Co=16
set number
set mouse=nvc

hi! LineNr ctermbg=0 ctermfg=10

let g:solarized_termcolors=16

EndOfMessage


curl https://raw.githubusercontent.com/mbbill/undotree/master/plugin/undotree.vim
echo

curl https://raw.githubusercontent.com/mbbill/undotree/master/syntax/undotree.vim
echo

curl https://raw.githubusercontent.com/tpope/vim-surround/master/plugin/surround.vim
echo

curl https://raw.githubusercontent.com/hdima/python-syntax/master/syntax/python.vim
echo

curl https://raw.githubusercontent.com/tpope/vim-rsi/master/plugin/rsi.vim
echo

curl https://raw.githubusercontent.com/tpope/vim-eunuch/master/plugin/eunuch.vim
echo

curl https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim 
echo

curl https://raw.githubusercontent.com/tpope/vim-commentary/master/plugin/commentary.vim
echo

curl https://raw.githubusercontent.com/tpope/vim-sleuth/master/plugin/sleuth.vim
echo

cat << EndOfMessage

" Highlight VCS conflict markers
hi VCSConflict ctermfg=8 ctermbg=9
match VCSConflict '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$' " seems to get overwritte by PythonExtraOperator

hi TrailingWhitespace cterm=bold ctermfg=15
match TrailingWhitespace '\s\+$'

hi ErrorMsg ctermfg=8 ctermbg=9

au FileType python execute "setlocal colorcolumn=" . join(range(95,335), ',')
au FileType python setlocal completeopt-=preview
au FileType undotree setlocal statusline=
au FileType diff setlocal statusline=

" solarized colors
" syntax match Red "Red" containedin=vimHiGroup,vimHiKeyList
hi Base02  ctermfg=0 ctermbg=NONE cterm=NONE
hi Red     ctermfg=1 ctermbg=NONE cterm=NONE
hi Green   ctermfg=2 ctermbg=NONE cterm=NONE
hi Yellow  ctermfg=3 ctermbg=NONE cterm=NONE
hi Blue    ctermfg=4 ctermbg=NONE cterm=NONE
hi Magenta ctermfg=5 ctermbg=NONE cterm=NONE
hi Cyan    ctermfg=6 ctermbg=NONE cterm=NONE
hi Base2   ctermfg=7 ctermbg=NONE cterm=NONE
hi Orange  ctermfg=9 ctermbg=NONE cterm=NONE
hi Base01  ctermfg=10 ctermbg=NONE cterm=NONE
hi Base00  ctermfg=11 ctermbg=NONE cterm=NONE
hi Violet  ctermfg=13 ctermbg=NONE cterm=NONE
hi Base1   ctermfg=14 ctermbg=NONE cterm=NONE
hi Base3   ctermfg=15 ctermbg=NONE cterm=NONE

hi SmallGrey ctermbg=8 ctermfg=10
hi Grey ctermbg=8 ctermfg=10 cterm=NONE
hi SmallBlue ctermfg=4 ctermbg=NONE
hi link White Base3

hi ColorColumn ctermbg=0
hi CursorLineNr ctermfg=0 ctermbg=3 cterm=bold
hi MatchParen ctermbg=8 ctermfg=5
hi NonText ctermbg=0 ctermbg=0
hi SpecialKey ctermbg=NONE ctermfg=10
hi NonText ctermbg=8
hi Folded ctermbg=8 cterm=NONE ctermbg=8 ctermfg=14
hi Visual ctermfg=12 ctermbg=NONE
hi ModeMsg ctermbg=3 ctermfg=8
hi Todo ctermfg=3
hi SpellBad cterm=undercurl

" hi PythonImport ctermbg=NONE ctermfg=3 cterm=NONE
" hi link pythonClassParameters pythonClass

" hi link Type Blue

hi link PythonFloat Violet
hi link PythonNumber Violet
hi link PythonBuiltinObj Violet
hi link pythonOctNumber Violet
hi link pythonBinNumber Violet

hi link PythonExtraOperator Base00
hi link pythonDot Base00

hi link PythonClass Green
hi link PythonException Blue
hi link PythonFunction Yellow
hi link PythonInclude Magenta
hi link PythonRepeat Blue
hi link PythonSelf Base00
hi link PythonStatement Blue
hi link pythonBuiltinFunc Normal
hi link pythonBuiltinType Blue
hi link pythonConditional Blue
hi link pythonEscape PythonString
hi link pythonExClass Orange
hi link pythonExtraPseudoOperator Blue
hi link pythonOperator Blue
hi link pythonStrFormat Normal
hi link pythonStrFormatting Normal
hi link pythonStrTemplate PythonString
hi link pythonDocTest2 PythonString
hi link pythonDocstring PythonString
hi pythonTodo ctermfg=15 ctermbg=8
hi link pythonRun Grey
hi link PythonDecorator Magenta
hi link PythonDottedName Magenta

hi htmlLink ctermfg=4
hi link htmlSpecialChar Base2
" hi htmlArg ctermfg=14
hi link htmlH1 White
hi link htmlH2 White
hi link htmlH3 White
hi link htmlH4 White
hi link htmlH5 White
hi link htmlH6 White
hi htmlTagName ctermfg=6
hi htmlSpecialTagName ctermfg=9
hi htmlTagN ctermfg=6
hi htmlTag ctermfg=6
hi htmlEndTag ctermfg=6
hi htmlComment ctermfg=10
hi htmlCommentPart ctermfg=10

hi jsGlobalObjects ctermfg=7
hi jsFunction ctermfg=4
hi jsStorageClass ctermfg=4

hi djangoTagBlock ctermfg=2
hi djangoStatement ctermfg=2
hi djangoArgument ctermfg=2
hi djangoFilter ctermfg=2
hi djangoVarBlock ctermfg=2

hi link UndotreeTimeStamp Normal
hi link UndotreeSavedSmall Blue
hi link UndotreeSavedBig Yellow
hi link UndotreeNext Normal
hi link UndotreeCurrent Normal
hi link UndotreeHEad Normal
hi link UndotreeNodeCurrent Yellow
hi link UndotreeCurrent Yellow

hi link diffRemoved Orange

hi StatusLineFile ctermbg=10 ctermfg=8
hi StatusLineFileReversed ctermbg=8 ctermfg=10
hi Invisible ctermbg=8 ctermfg=8
hi StatusLineASCIIScrollbar ctermfg=10
" bold is a hack, statuslineNC and statusline cant be the same hilight
" not sure, why StatusLineNC needs the oposite than StatusLine, but it works
hi StatusLineNC ctermbg=8 ctermfg=14 cterm=bold
hi StatusLine ctermbg=14 ctermfg=8
hi VertSplit ctermfg=14 ctermbg=8

hi link helpCommand Blue
hi link qfLineNr SmallGrey
hi link qfSeparator Invisible

function! Update()
  hi SignColumn ctermbg=8
  hi clear CursorLine
  hi CursorLine ctermbg=0
  hi SyntasticError ctermbg=0 cterm=underline
  hi SyntasticErrorSign ctermfg=1 ctermbg=8
  hi SyntasticWarningSign ctermfg=9 ctermbg=8
  hi SyntasticStyleErrorSign ctermfg=12 ctermbg=8
  hi SyntasticStyleWarningSign ctermfg=12 ctermbg=8

endfunction

call Update()
au Syntax * Update
" au VimEnter * Update " makes vim always jump to top when opened. do i need this?

" make sign column always visible
function! PlaceDummySign()
  if &buftype != "nofile"
    sign define dummy
    execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
endif
endfunction
au BufEnter * call PlaceDummySign()

au WinEnter * set cursorline
au WinLeave * set nocursorline

EndOfMessage
